[Feat] cat animation#18
RollingPaper42/Front-End pull request #136
Opened 2023-11-28 12:43 UTC by Arkingco

# Describe your changes
- 고양이 애니메이션 구현
  - personal 페이지에 CatAnimation 컴포넌트 추가 
    - cat animation이 활성화 여부를 cat recoil state로 선언
    - 전역 cat 상태를 업데이트 하는 useCat 구현
      - setCat원하는 위치의 element, action, 시간을 받아서 업데이트
  - personal 페이지에 strcatAnimationHeader 로 header 파일 분리
 
### 위치 특정 로직
  - 위치를 특정하는 기준은 각 화면에 있는 element 요소의 top, left 값을 기준으로 함
     - 앱 바 탈출 고양이 애니메이션 => 헤더 div
     - 생성하기 버튼 위 애니에미션 => 버튼 컴포넌트 부모 div
      - 원하는 element의 top left 값을 구해서 애니메이션  Image의 top left 를 지정해줌 현재 디자인의 레이아웃에
        - left-margin 24px
        - right-margin 24 px
        - top-margin 8px 
        - 를 계산한 위치에 gif 배치
## Screen Capture

# Issue number and link
- #18

2023-11-28 14:36 UTC, lamPolar requested changes
파일 이름에 cat을 쓰는 곳이 많다고 하신게 기억이 나서, 혹시 animation는 어떨까요?

2023-11-28 14:36 UTC, lamPolar commented on src/component/StrcatAnimationHeader.tsx
> +              <Image
이부분 어제 수정으로 svg 컴포넌트 가져오는 걸로 변경되었습니다!

2023-11-28 14:36 UTC, lamPolar commented on src/component/StrcatAnimationHeader.tsx
> +            src={`/ProfileImg_${theme.name}.svg`}
profileimg가져오는 부분도 수정되었어요! 이대로 머지하시면 어제 삭제한 파일들 때문에 깨져보일 것 같습니다!

2023-11-28 16:08 UTC, lyssoi approved these changes

2023-11-29 03:38 UTC, Arkingco commented
> 파일 이름에 cat을 쓰는 곳이 많다고 하신게 기억이 나서, 혹시 animation는 어떨까요?

말씀하신 부분이 catAnimation 인지 아니면 cat -> animation 으로 변경 하자는 얘기이신지 모르겠지만 만약
- cat이 animation으로 변경 된다면 animation이라는 이름이 가지고 있는 범위가 너무 넓은 것 같다고 느껴지고 cat의 animation을 변경하는 작업이라고 생각이 들지 않을 것 같습니당
- catAnimation으로 변경하는 작업 이라면 희선님이 작성하신 catTheme도 catImage로 변경하여
  - catImage.ts
  - catAnimation.ts
  - 형식으로 작업하는건 구분되는 방식이 통일성 있다고 느껴져서 좋아보여요!

catAnimation으로 변경하고 다시 올리겟습니다!

2023-11-29 03:39 UTC, Arkingco commented on src/component/StrcatAnimationHeader.tsx
> +              <Image
변경하겠습니다!

2023-11-29 03:39 UTC, Arkingco commented on src/component/StrcatAnimationHeader.tsx
> +            src={`/ProfileImg_${theme.name}.svg`}
변경하겠습니다!!

2023-11-29 04:10 UTC, dokoh1 commented
수구하셨습니다.

2023-11-29 04:10 UTC, dokoh1 approved these changes

2023-11-29 05:58 UTC, lamPolar approved these changes
변경사항 확인했습니다! 수고하셨습니다:) 고양이 너무 귀엽네요

2023-11-29 05:59 UTC, merged