[Feat]create_page 구현 및 textarea 수정#229
RollingPaper42/Front-End pull request #251
Opened 2023-12-13 10:49 UTC by dokoh1

# Describe your changes
1. textarea의 h-min max를 추가하였습니다.
2. create page에서 overscroll를 이용하여 가로스크롤을 구현하였습니다.
3. hidden css를 통해 create 페이지에 createTheme 컴포넌트를 추가하였습니다.
4. overscoll에 있는 카드 선택 시 hidden을 통해 title 예시를 표시하였습니다.
5. title 예시 클릭 시 해당 예시가 textarea에 입력되도록 설정하였습니다.
6. 테마 선택 시 미리보기 이미지를 볼 수 있게 설정하였습니다.
## Screen Capture
<img width="341" alt="image" src="https://github.com/RollingPaper42/Front-End/assets/146950802/17d995a1-b1cd-49a2-85f6-98b074a823a9">
<img width="341" alt="image" src="https://github.com/RollingPaper42/Front-End/assets/146950802/6e6eac4d-0b5f-4451-a6cf-60d79a52ab5c">

# Issue number and link
- #229

2023-12-13 11:08 UTC, Arkingco approved these changes

2023-12-13 11:08 UTC, Arkingco approved these changes
확인했습니다!!

2023-12-13 11:35 UTC, lyssoi approved these changes

2023-12-13 12:23 UTC, lamPolar requested changes
수고하셨습니다! 
create 페이지 배포가 기대되네요~
남긴 코멘트 확인해주시고, 수정해주시면 좋겠습니다!

2023-12-13 12:23 UTC, lamPolar commented on src/app/create/page.tsx
> +    setIsOff((prevIsOff) => (prevIsOff === value ? '' : value));
isOff를 어떤 테마를 선택했는지에 대한 상태값으로 사용하고 계신것 같은데, 변수명이 좀더 직관적이면 좋을 것 같습니다!
그리고, handleSwitch에서 테마 선택시 on / off방식을 택하고 계신것 같은데, 
그냥 클릭하면 무조건 그 테마를 선택한걸로 변경하면 어떨까요?
코드상으로는 setIsOff(value)가 될 것 같습니다.

2023-12-13 12:23 UTC, lamPolar commented on src/component/BottomButton.tsx
> +      } ${textColor} rounded-[5px] relative mx-1 ${height} w-full ${width} ${
이전버전에서 삭제했었는데, mx-1 속성이 다시 생겼네요ㅎㅎ
제거 부탁드립니다!

2023-12-13 12:23 UTC, lamPolar commented on src/component/CreateTheme.tsx
> +            alt="kakao"
이 부분의 Image태그들 alt값 변경 부탁드립니다.
반복 코드가 많은데, 이미지를 띄우는 부분을 하나의 컴포넌트로 분리해서 배열의 index로 이미지를 가져오면 코드가 한결 간결해질 것 같습니다! 한번 고려해봐주세요:)

2023-12-13 12:23 UTC, lamPolar commented on src/component/Textarea.tsx
> +  maxheight,
add 페이지에서 Textarea를 사용하는 부분에서는 이부분 수정이 안들어간 상태라서, npm run build가 안될 수 있겠네요...!

2023-12-14 03:55 UTC, dokoh1 commented on src/component/BottomButton.tsx
> +      } ${textColor} rounded-[5px] relative mx-1 ${height} w-full ${width} ${
수정하였습니다.

2023-12-14 03:56 UTC, dokoh1 commented on src/app/create/page.tsx
> +    setIsOff((prevIsOff) => (prevIsOff === value ? '' : value));
잘못 인지하고 계신거같아 말씀드립니다. handleswitch 함수는
![image](https://github.com/RollingPaper42/Front-End/assets/146950802/d87265b0-ad0b-4238-9333-a9d0c46f8969)
이 쪽 on/off 기능을 구현하고 있는 함수입니다.

2023-12-14 03:58 UTC, dokoh1 commented on src/component/CreateTheme.tsx
> +            alt="kakao"
수정하였습니다. 일단 index로 이미지를 가져오는 방식이 되게 좋을꺼같아 숫자로 alt값을 변경하였고 차후에 리팩토링 시 수정하겠습니다.

2023-12-14 04:00 UTC, dokoh1 commented on src/component/Textarea.tsx
> +  maxheight,
npm run build 했을 때는 문제 없었습니다.

2023-12-14 06:12 UTC, closed without merging